# Generated by Django 3.1.2 on 2020-10-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20201017_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='الصوره'),
        ),
    ]
