# Generated by Django 3.1.2 on 2020-10-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
